# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/aerotenna/desktop/axi_ocpoc/axi_ocpoc_pwm_controller_1.0/axi_ocpoc_pwm_controller_v1_0_project/AXI_OcPoC_PWM_Controller_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/aerotenna/desktop/axi_ocpoc/axi_ocpoc_pwm_controller_1.0/axi_ocpoc_pwm_controller_v1_0_project/AXI_OcPoC_PWM_Controller_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/Aerotenna/Desktop/ocpoc_rev1_6pin/ip_repo/pwm_chan_1.0
  c:/Users/Aerotenna/Desktop/AXI_OcPoC
  c:/Users/Aerotenna/Desktop/ocpoc_rev1_6pin/ocpoc_rev1/ocpoc_rev1.tmp/ip_repo
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  c:/users/aerotenna/desktop/axi_ocpoc/axi_ocpoc_pwm_controller_1.0/src/pwm_chan.v
  c:/users/aerotenna/desktop/axi_ocpoc/axi_ocpoc_pwm_controller_1.0/hdl/AXI_OcPoC_PWM_Controller_v1_0_S00_AXI.v
  c:/users/aerotenna/desktop/axi_ocpoc/axi_ocpoc_pwm_controller_1.0/hdl/AXI_OcPoC_PWM_Controller_v1_0.v
}
synth_design -top AXI_OcPoC_PWM_Controller_v1_0 -part xc7z010clg400-1
write_checkpoint -noxdef AXI_OcPoC_PWM_Controller_v1_0.dcp
catch { report_utilization -file AXI_OcPoC_PWM_Controller_v1_0_utilization_synth.rpt -pb AXI_OcPoC_PWM_Controller_v1_0_utilization_synth.pb }
