# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ocpoc_rev1.xdc

# Block Designs: bd/armps/armps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps || ORIG_REF_NAME==armps}]

# IP: bd/armps/ip/armps_processing_system7_0_0/armps_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_processing_system7_0_0 || ORIG_REF_NAME==armps_processing_system7_0_0}]

# IP: bd/armps/ip/armps_processing_system7_0_axi_periph_0/armps_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==armps_processing_system7_0_axi_periph_0}]

# IP: bd/armps/ip/armps_rst_processing_system7_0_50M_0/armps_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==armps_rst_processing_system7_0_50M_0}]

# IP: bd/armps/ip/armps_axi_uart16550_0_0/armps_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_0_0 || ORIG_REF_NAME==armps_axi_uart16550_0_0}]

# IP: bd/armps/ip/armps_axi_uart16550_0_1/armps_axi_uart16550_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_0_1 || ORIG_REF_NAME==armps_axi_uart16550_0_1}]

# IP: bd/armps/ip/armps_axi_uart16550_1_0/armps_axi_uart16550_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_1_0 || ORIG_REF_NAME==armps_axi_uart16550_1_0}]

# IP: bd/armps/ip/armps_axi_uart16550_1_1/armps_axi_uart16550_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_1_1 || ORIG_REF_NAME==armps_axi_uart16550_1_1}]

# IP: bd/armps/ip/armps_axi_iic_0_0/armps_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_iic_0_0 || ORIG_REF_NAME==armps_axi_iic_0_0}]

# IP: bd/armps/ip/armps_xadc_wiz_0_0/armps_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_xadc_wiz_0_0 || ORIG_REF_NAME==armps_xadc_wiz_0_0}]

# IP: bd/armps/ip/armps_xlconcat_0_0/armps_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_xlconcat_0_0 || ORIG_REF_NAME==armps_xlconcat_0_0}]

# IP: bd/armps/ip/armps_axi_uart16550_4_0/armps_axi_uart16550_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_4_0 || ORIG_REF_NAME==armps_axi_uart16550_4_0}]

# IP: bd/armps/ip/armps_axi_uart16550_4_1/armps_axi_uart16550_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_4_1 || ORIG_REF_NAME==armps_axi_uart16550_4_1}]

# IP: bd/armps/ip/armps_axi_uart16550_5_0/armps_axi_uart16550_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_5_0 || ORIG_REF_NAME==armps_axi_uart16550_5_0}]

# IP: bd/armps/ip/armps_axi_uart16550_6_0/armps_axi_uart16550_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_6_0 || ORIG_REF_NAME==armps_axi_uart16550_6_0}]

# IP: bd/armps/ip/armps_axi_iic_0_1/armps_axi_iic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_iic_0_1 || ORIG_REF_NAME==armps_axi_iic_0_1}]

# IP: bd/armps/ip/armps_axi_iic_1_0/armps_axi_iic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_iic_1_0 || ORIG_REF_NAME==armps_axi_iic_1_0}]

# IP: bd/armps/ip/armps_axi_iic_1_1/armps_axi_iic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_axi_iic_1_1 || ORIG_REF_NAME==armps_axi_iic_1_1}]

# IP: bd/armps/ip/armps_xlconstant_0_0/armps_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_xlconstant_0_0 || ORIG_REF_NAME==armps_xlconstant_0_0}]

# IP: bd/armps/ip/armps_xlconstant_1_0/armps_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_xlconstant_1_0 || ORIG_REF_NAME==armps_xlconstant_1_0}]

# IP: bd/armps/ip/armps_rst_processing_system7_0_50M_1_0/armps_rst_processing_system7_0_50M_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_rst_processing_system7_0_50M_1_0 || ORIG_REF_NAME==armps_rst_processing_system7_0_50M_1_0}]

# IP: bd/armps/ip/armps_AXI_OcPoC_PWM_Controller_0_0/armps_AXI_OcPoC_PWM_Controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_AXI_OcPoC_PWM_Controller_0_0 || ORIG_REF_NAME==armps_AXI_OcPoC_PWM_Controller_0_0}]

# IP: bd/armps/ip/armps_RC_Receiver_Input_0_0_1/armps_RC_Receiver_Input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_RC_Receiver_Input_0_0 || ORIG_REF_NAME==armps_RC_Receiver_Input_0_0}]

# IP: bd/armps/ip/armps_xbar_0/armps_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_xbar_0 || ORIG_REF_NAME==armps_xbar_0}]

# IP: bd/armps/ip/armps_auto_cc_1/armps_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_auto_cc_1 || ORIG_REF_NAME==armps_auto_cc_1}]

# IP: bd/armps/ip/armps_auto_cc_0/armps_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_auto_cc_0 || ORIG_REF_NAME==armps_auto_cc_0}]

# IP: bd/armps/ip/armps_auto_pc_0/armps_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==armps_auto_pc_0 || ORIG_REF_NAME==armps_auto_pc_0}]

# XDC: bd/armps/ip/armps_processing_system7_0_0/armps_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_processing_system7_0_0 || ORIG_REF_NAME==armps_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/armps/ip/armps_rst_processing_system7_0_50M_0/armps_rst_processing_system7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==armps_rst_processing_system7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_rst_processing_system7_0_50M_0/armps_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==armps_rst_processing_system7_0_50M_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_rst_processing_system7_0_50M_0/armps_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/armps/ip/armps_axi_uart16550_0_0/armps_axi_uart16550_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_0_0 || ORIG_REF_NAME==armps_axi_uart16550_0_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_0_0/armps_axi_uart16550_0_0_ooc.xdc

# XDC: bd/armps/ip/armps_axi_uart16550_0_0/armps_axi_uart16550_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_0_0 || ORIG_REF_NAME==armps_axi_uart16550_0_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_0_1/armps_axi_uart16550_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_0_1 || ORIG_REF_NAME==armps_axi_uart16550_0_1}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_0_1/armps_axi_uart16550_0_1_ooc.xdc

# XDC: bd/armps/ip/armps_axi_uart16550_0_1/armps_axi_uart16550_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_0_1 || ORIG_REF_NAME==armps_axi_uart16550_0_1}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_1_0/armps_axi_uart16550_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_1_0 || ORIG_REF_NAME==armps_axi_uart16550_1_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_1_0/armps_axi_uart16550_1_0_ooc.xdc

# XDC: bd/armps/ip/armps_axi_uart16550_1_0/armps_axi_uart16550_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_1_0 || ORIG_REF_NAME==armps_axi_uart16550_1_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_1_1/armps_axi_uart16550_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_1_1 || ORIG_REF_NAME==armps_axi_uart16550_1_1}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_1_1/armps_axi_uart16550_1_1_ooc.xdc

# XDC: bd/armps/ip/armps_axi_uart16550_1_1/armps_axi_uart16550_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_1_1 || ORIG_REF_NAME==armps_axi_uart16550_1_1}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_iic_0_0/armps_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_iic_0_0 || ORIG_REF_NAME==armps_axi_iic_0_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_iic_0_0/armps_axi_iic_0_0_ooc.xdc

# XDC: bd/armps/ip/armps_xadc_wiz_0_0/armps_xadc_wiz_0_0_ooc.xdc

# XDC: bd/armps/ip/armps_xadc_wiz_0_0/armps_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_xadc_wiz_0_0 || ORIG_REF_NAME==armps_xadc_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/armps/ip/armps_axi_uart16550_4_0/armps_axi_uart16550_4_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_4_0 || ORIG_REF_NAME==armps_axi_uart16550_4_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_4_0/armps_axi_uart16550_4_0_ooc.xdc

# XDC: bd/armps/ip/armps_axi_uart16550_4_0/armps_axi_uart16550_4_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_4_0 || ORIG_REF_NAME==armps_axi_uart16550_4_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_4_1/armps_axi_uart16550_4_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_4_1 || ORIG_REF_NAME==armps_axi_uart16550_4_1}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_4_1/armps_axi_uart16550_4_1_ooc.xdc

# XDC: bd/armps/ip/armps_axi_uart16550_4_1/armps_axi_uart16550_4_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_4_1 || ORIG_REF_NAME==armps_axi_uart16550_4_1}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_5_0/armps_axi_uart16550_5_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_5_0 || ORIG_REF_NAME==armps_axi_uart16550_5_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_5_0/armps_axi_uart16550_5_0_ooc.xdc

# XDC: bd/armps/ip/armps_axi_uart16550_5_0/armps_axi_uart16550_5_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_5_0 || ORIG_REF_NAME==armps_axi_uart16550_5_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_6_0/armps_axi_uart16550_6_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_6_0 || ORIG_REF_NAME==armps_axi_uart16550_6_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_uart16550_6_0/armps_axi_uart16550_6_0_ooc.xdc

# XDC: bd/armps/ip/armps_axi_uart16550_6_0/armps_axi_uart16550_6_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_uart16550_6_0 || ORIG_REF_NAME==armps_axi_uart16550_6_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_iic_0_1/armps_axi_iic_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_iic_0_1 || ORIG_REF_NAME==armps_axi_iic_0_1}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_iic_0_1/armps_axi_iic_0_1_ooc.xdc

# XDC: bd/armps/ip/armps_axi_iic_1_0/armps_axi_iic_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_iic_1_0 || ORIG_REF_NAME==armps_axi_iic_1_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_iic_1_0/armps_axi_iic_1_0_ooc.xdc

# XDC: bd/armps/ip/armps_axi_iic_1_1/armps_axi_iic_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_axi_iic_1_1 || ORIG_REF_NAME==armps_axi_iic_1_1}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_axi_iic_1_1/armps_axi_iic_1_1_ooc.xdc

# XDC: bd/armps/ip/armps_rst_processing_system7_0_50M_1_0/armps_rst_processing_system7_0_50M_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_rst_processing_system7_0_50M_1_0 || ORIG_REF_NAME==armps_rst_processing_system7_0_50M_1_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_rst_processing_system7_0_50M_1_0/armps_rst_processing_system7_0_50M_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_rst_processing_system7_0_50M_1_0 || ORIG_REF_NAME==armps_rst_processing_system7_0_50M_1_0}] {/U0 }]/U0 ]]

# XDC: bd/armps/ip/armps_rst_processing_system7_0_50M_1_0/armps_rst_processing_system7_0_50M_1_0_ooc.xdc

# XDC: bd/armps/ip/armps_xbar_0/armps_xbar_0_ooc.xdc

# XDC: bd/armps/ip/armps_auto_cc_1/armps_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_auto_cc_1 || ORIG_REF_NAME==armps_auto_cc_1}] {/inst }]/inst ]]

# XDC: bd/armps/ip/armps_auto_cc_1/armps_auto_cc_1_ooc.xdc

# XDC: bd/armps/ip/armps_auto_cc_0/armps_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==armps_auto_cc_0 || ORIG_REF_NAME==armps_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/armps/ip/armps_auto_cc_0/armps_auto_cc_0_ooc.xdc

# XDC: bd/armps/ip/armps_auto_pc_0/armps_auto_pc_0_ooc.xdc

# XDC: bd/armps/armps_ooc.xdc
